# CSV Files and Data Frames

This exercise should get you started with handling data in Python. There is no data analysis yet, just some loading and filtering of the data. 


## Loading data from CSV
Your first step is always accessing the data. Often, the data is stored in a database or within files. One common and generic exchange format for files are Comma Separated Value (CSV) files. The first line of such a file indicates the names of the features, the following lines each contain a single instance.

First, download the ```analcatdata_bankruptcy``` dataset in the data folder and and upload it to your Jupyter notebook. 

Use the cell below to load the data from the CSV file. The data should be loaded into a _data frame_. Data frames are available in python using the ```pandas``` library. In comparison to matrices or similar types, they allow different types of columns, are usually easier to manipulate, e.g., by adding or removing rows/columns, and rows and columns can be named. 

Once you have done this, print some information about the data:
- number of instances
- number of features
- names of the features

In [9]:
%pip install pandas

import pandas as pd
data = pd.read_csv('analcatdata_bankruptcy.csv')
data.head()

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\gitik\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\gitik\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\gitik\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\gitik\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\gitik\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\gitik\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: C:\Users\gitik\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

                     Company  WC/TA  RE/TA  EBIT/TA  S/TA  BVE/BVL  Bankrupt
0                360Networks    9.3   -7.7      1.6   9.1    3.726         1
1     Advanced_Radio_Telecom   42.6  -60.1    -10.1   0.3    4.130         1
2      Ardent_Communications  -28.8 -203.2    -51.0  14.7    0.111         1
3              At_Home_Corp.    2.5 -433.1     -6.0  29.3    1.949         1
4  Convergent_Communications   26.1  -57.4    -23.5  54.2    0.855         1

In [10]:

print('Number of instances(rows):', data.shape[0])
print('Number of features(columns) :', data.shape[1])
print('Feature names      :', list(data.columns))

Number of instances(rows): 50
Number of features(columns) : 7
Feature names      : ['Company', 'WC/TA', 'RE/TA', 'EBIT/TA', 'S/TA', 'BVE/BVL', 'Bankrupt']

## Remove features

If you load all data from a file, you often also load irrelevant features for a task. In case of the data you just loaded, the feature is called ```Company```. This is an ID feature for the instances in the data. Such data must often be removed before further analysis of the data. Your second task is to remove this feature from the data.

In [17]:

data.columns = data.columns.str.strip().map(lambda c: c.lstrip('\ufeff'))

if 'Company' in data.columns:
    data.drop('Company', axis=1, inplace=True)
else:
    print("Column 'Company' not present (already removed or different name). Columns:", list(data.columns))

data.head()

Column 'Company' not present (already removed or different name). Columns: ['WC/TA', 'RE/TA', 'EBIT/TA', 'S/TA', 'BVE/BVL', 'Bankrupt']

   WC/TA  RE/TA  EBIT/TA  S/TA  BVE/BVL  Bankrupt
0    9.3   -7.7      1.6   9.1    3.726         1
1   42.6  -60.1    -10.1   0.3    4.130         1
2  -28.8 -203.2    -51.0  14.7    0.111         1
3    2.5 -433.1     -6.0  29.3    1.949         1
4   26.1  -57.4    -23.5  54.2    0.855         1

## Remove instances with missing values

Real-life data is often not clean, i.e., the data has many problems which must be addressed first, before it can be used for analysis. One common problem are missing features, i.e., not all features are available for all data. This is also the case for the data you just loaded. All missing values are marked as NA in the CSV file. 

Your third task is to remove all instances from the data, that have any missing values and store the remaining instances in a new data frame. If this works correctly, five instances should be removed. You can check this, e.g., by comparing the sizes of the data frames or printing the instances that were removed.

In [19]:
print('No. of instances before dropping misisng values instances:', data.shape[0]   )
data.dropna(inplace=True)
print('No. of instances after dropping misisng values instances:', data.shape[0]  )

No. of instances before dropping misisng values instances: 50
No. of instances after dropping misisng values instances: 50

## Computing with data frames

Sometimes you have to compute new columns from the values of existing columns. Please append two new columns to the data frame: The sum of the columns WC/TA and RE/TA and the product of the columns EBIT/TA and S/TA.

In [22]:
data['WC/TA + RE/TA'] = data['WC/TA'] + data['RE/TA']
data.loc[:,'EBIT/TA*S/TA'] = data.loc[:,'EBIT/TA'] * data.loc[:,'S/TA']
data

,WC/TA,RE/TA,EBIT/TA,S/TA,BVE/BVL,Bankrupt,WC/TA + RE/TA,EBIT/TA*S/TA
0,9.3,-7.7,1.6,9.1,3.726,1,1.6,14.56
1,42.6,-60.1,-10.1,0.3,4.130,1,-17.5,-3.03
2,-28.8,-203.2,-51.0,14.7,0.111,1,-232.0,-749.70
3,2.5,-433.1,-6.0,29.3,1.949,1,-430.6,-175.80
4,26.1,-57.4,-23.5,54.2,0.855,1,-31.3,-1273.70
5,39.2,-111.8,-77.8,10.5,0.168,1,-72.6,-816.90
6,-5.4,-105.2,-5.8,38.9,0.028,1,-110.6,-225.62
7,-35.2,-92.4,-32.5,48.5,11.280,1,-127.6,-1576.25
8,10.5,-12.4,-2.3,21.0,2.500,1,-1.9,-48.30
9,-22.4,-124.5,-7.9,125.6,1.595,1,-146.9,-992.24
10,24.6,-29.0,-2.0,21.3,1.968,1,-4.4,-42.60
11,6.6,-50.9,-2.6,28.9,0.258,1,-44.3,-75.14
12,33.9,-46.5,-17.5,0.9,0.828,1,-12.6,-15.75
13,19.1,-66.3,-25.5,22.3,0.460,1,-47.2,-568.65
14,-21.1,-46.0,-26.8,81.4,0.698,1,-67.1,-2181.52
15,2.5,-228.7,-6.7,38.6,0.030,1,-226.2,-258.62
16,47.0,-78.2,-42.0,4.4,0.168,1,-31.2,-184.80
17,9.1,-40.2,-0.7,81.5,0.522,1,-31.1,-57.05
18,43.0,-49.2,-87.4,119.9,2.919,1,-6.2,-10479.26
19,-34.9,-79.0,-13.5,127.8,0.197,1,-113.9,-1725.30
20,20.6,-146.3,-36.0,12.6,0.075,1,-125.7,-453.60
21,-51.6,-326.1,-98.7,0.9,2.402,1,-377.7,-88.83
22,-93.0,-95.2,-7.3,34.8,0.071,1,-188.2,-254.04
23,-127.5,-121.3,6.4,65.7,0.248,1,-248.8,420.48
24,-1.2,-47.5,-9.7,14.5,0.456,1,-48.7,-140.65
25,30.6,-14.4,-4.9,2.2,3.482,0,16.2,-10.78
26,9.8,-33.8,-7.1,3.2,5.965,0,-24.0,-22.72
27,37.8,-45.4,-7.1,17.1,3.450,0,-7.6,-121.41
28,2.2,31.6,22.0,58.0,2.758,0,33.8,1276.00
29,-11.5,27.6,24.4,51.4,2.266,0,16.1,1254.16
30,-4.1,-5.8,7.7,31.6,1.222,0,-9.9,243.32
31,-5.7,21.1,14.3,28.9,1.153,0,15.4,413.27
32,25.2,0.0,7.9,25.9,0.717,0,25.2,204.61
33,-5.7,0.0,16.3,49.9,1.517,0,-5.7,813.37
34,1.7,11.4,14.1,48.0,1.347,0,13.1,676.80
35,13.8,-37.6,-13.0,32.3,13.768,0,-23.8,-419.90
36,8.2,-15.6,0.3,87.7,5.444,0,-7.4,26.31
37,74.7,54.6,27.9,74.6,3.720,0,129.3,2081.34
38,43.1,-0.4,3.4,40.0,0.925,0,42.7,136.00
39,48.7,38.4,-9.2,65.4,0.705,0,87.1,-601.68
40,40.7,0.6,1.8,49.2,7.497,0,41.3,88.56
41,20.3,-61.3,1.9,27.0,35.178,0,-41.0,51.30
42,16.1,3.6,11.6,21.4,0.856,0,19.7,248.24
43,-6.1,0.0,9.4,22.6,2.123,0,-6.1,212.44
44,-7.2,18.6,20.8,52.2,2.413,0,11.4,1085.76
45,-5.3,31.0,4.9,26.9,1.362,0,25.7,131.81
46,4.1,-10.1,9.7,36.0,7.623,0,-6.0,349.20
47,0.3,27.9,16.1,49.5,4.357,0,28.2,796.95
48,-7.4,8.9,15.3,39.3,1.273,0,1.5,601.29
49,1.1,-39.5,15.7,41.8,1.449,0,-38.4,656.26

## Merging data frames

The next task of this exercise is to merge data frames. For this, load the data from the same CSV file as above again. Then merge the data frame with the result from task 2.4, such that:
- the dropped feature from task 2.2 is part of the merged data frame; and
- the removed instances from task 2.3 are still gone; and
- the indirectly computed features from task 2.4 are part of the merged data frame.

In [23]:
data2=pd.read_csv('analcatdata_bankruptcy.csv')
merged_data=data.merge(data2)
merged_data.head()

,WC/TA,RE/TA,EBIT/TA,S/TA,BVE/BVL,Bankrupt,WC/TA + RE/TA,EBIT/TA*S/TA,Company
0,9.3,-7.7,1.6,9.1,3.726,1,1.6,14.56,360Networks
1,42.6,-60.1,-10.1,0.3,4.130,1,-17.5,-3.03,Advanced_Radio_Telecom
2,-28.8,-203.2,-51.0,14.7,0.111,1,-232.0,-749.70,Ardent_Communications
3,2.5,-433.1,-6.0,29.3,1.949,1,-430.6,-175.80,At_Home_Corp.
4,26.1,-57.4,-23.5,54.2,0.855,1,-31.3,-1273.70,Convergent_Communications

## Selecting subsets

Based on the data frame from task 2.5, create new data frames according to the following criteria.
- A data frame with only the rows 10 to 20 and all columns. 
- A data frame with only the columns 1 to 4 and all rows. 
- A data frame with only the columns WC/TA and EBIT/TA and all rows. 
- A data frame with all rows that have the value RE/TA less than -20 and all columns.
- A data frame with all rows that have the value RE/TA less than -20 and bankrupt equal to 0 and all columns. 
- A data frame with all rows that have the value RE/TA less than -20 and bankrupt equal to 0 and only the columns WC/TA and EBIT/TA.

In [25]:
print('df with rows 10-20 & all columns')
merged_data[10:21]

df with rows 10-20 & all columns

,WC/TA,RE/TA,EBIT/TA,S/TA,BVE/BVL,Bankrupt,WC/TA + RE/TA,EBIT/TA*S/TA,Company
10,24.6,-29.0,-2.0,21.3,1.968,1,-4.4,-42.60,Global_Telesystems
11,6.6,-50.9,-2.6,28.9,0.258,1,-44.3,-75.14,GST_Telecom
12,33.9,-46.5,-17.5,0.9,0.828,1,-12.6,-15.75,Metricom
13,19.1,-66.3,-25.5,22.3,0.460,1,-47.2,-568.65,Net2000_Communications
14,-21.1,-46.0,-26.8,81.4,0.698,1,-67.1,-2181.52,NetVoice_Technologies
15,2.5,-228.7,-6.7,38.6,0.030,1,-226.2,-258.62,PSINet
16,47.0,-78.2,-42.0,4.4,0.168,1,-31.2,-184.80,Rhythms_NetConnections
17,9.1,-40.2,-0.7,81.5,0.522,1,-31.1,-57.05,RSL_Communications
18,43.0,-49.2,-87.4,119.9,2.919,1,-6.2,-10479.26,SSE_Telecom
19,-34.9,-79.0,-13.5,127.8,0.197,1,-113.9,-1725.30,Startec_Global_Communications
20,20.6,-146.3,-36.0,12.6,0.075,1,-125.7,-453.60,Teligent

In [26]:
print('df with columns 1-4 and all rows')
merged_data.iloc[:, 1:5]

df with columns 1-4 and all rows

    RE/TA  EBIT/TA   S/TA  BVE/BVL
0    -7.7      1.6    9.1    3.726
1   -60.1    -10.1    0.3    4.130
2  -203.2    -51.0   14.7    0.111
3  -433.1     -6.0   29.3    1.949
4   -57.4    -23.5   54.2    0.855
5  -111.8    -77.8   10.5    0.168
6  -105.2     -5.8   38.9    0.028
7   -92.4    -32.5   48.5   11.280
8   -12.4     -2.3   21.0    2.500
9  -124.5     -7.9  125.6    1.595
10  -29.0     -2.0   21.3    1.968
11  -50.9     -2.6   28.9    0.258
12  -46.5    -17.5    0.9    0.828
13  -66.3    -25.5   22.3    0.460
14  -46.0    -26.8   81.4    0.698
15 -228.7     -6.7   38.6    0.030
16  -78.2    -42.0    4.4    0.168
17  -40.2     -0.7   81.5    0.522
18  -49.2    -87.4  119.9    2.919
19  -79.0    -13.5  127.8    0.197
20 -146.3    -36.0   12.6    0.075
21 -326.1    -98.7    0.9    2.402
22  -95.2     -7.3   34.8    0.071
23 -121.3      6.4   65.7    0.248
24  -47.5     -9.7   14.5    0.456
25  -14.4     -4.9    2.2    3.482
26  -33.8     -7.1    3.2    5.965
27  -45.4     -7.1   17.1    3.450
28   31.6     22.0   58.0    2.758
29   27.6     24.4   51.4    2.266
30   -5.8      7.7   31.6    1.222
31   21.1     14.3   28.9    1.153
32    0.0      7.9   25.9    0.717
33    0.0     16.3   49.9    1.517
34   11.4     14.1   48.0    1.347
35  -37.6    -13.0   32.3   13.768
36  -15.6      0.3   87.7    5.444
37   54.6     27.9   74.6    3.720
38   -0.4      3.4   40.0    0.925
39   38.4     -9.2   65.4    0.705
40    0.6      1.8   49.2    7.497
41  -61.3      1.9   27.0   35.178
42    3.6     11.6   21.4    0.856
43    0.0      9.4   22.6    2.123
44   18.6     20.8   52.2    2.413
45   31.0      4.9   26.9    1.362
46  -10.1      9.7   36.0    7.623
47   27.9     16.1   49.5    4.357
48    8.9     15.3   39.3    1.273
49  -39.5     15.7   41.8    1.449

In [27]:
print('df with all rows and columns WC/TA & EBIT/TA')
merged_data[ ['WC/TA', 'EBIT/TA']]

df with all rows and columns WC/TA & EBIT/TA

    WC/TA  EBIT/TA
0     9.3      1.6
1    42.6    -10.1
2   -28.8    -51.0
3     2.5     -6.0
4    26.1    -23.5
5    39.2    -77.8
6    -5.4     -5.8
7   -35.2    -32.5
8    10.5     -2.3
9   -22.4     -7.9
10   24.6     -2.0
11    6.6     -2.6
12   33.9    -17.5
13   19.1    -25.5
14  -21.1    -26.8
15    2.5     -6.7
16   47.0    -42.0
17    9.1     -0.7
18   43.0    -87.4
19  -34.9    -13.5
20   20.6    -36.0
21  -51.6    -98.7
22  -93.0     -7.3
23 -127.5      6.4
24   -1.2     -9.7
25   30.6     -4.9
26    9.8     -7.1
27   37.8     -7.1
28    2.2     22.0
29  -11.5     24.4
30   -4.1      7.7
31   -5.7     14.3
32   25.2      7.9
33   -5.7     16.3
34    1.7     14.1
35   13.8    -13.0
36    8.2      0.3
37   74.7     27.9
38   43.1      3.4
39   48.7     -9.2
40   40.7      1.8
41   20.3      1.9
42   16.1     11.6
43   -6.1      9.4
44   -7.2     20.8
45   -5.3      4.9
46    4.1      9.7
47    0.3     16.1
48   -7.4     15.3
49    1.1     15.7

In [28]:
print('df with all rows and columns where RE/TA<- 20')
merged_data[ merged_data['RE/TA'] < -20 ]

df with all rows and columns where RE/TA<- 20

,WC/TA,RE/TA,EBIT/TA,S/TA,BVE/BVL,Bankrupt,WC/TA + RE/TA,EBIT/TA*S/TA,Company
1,42.6,-60.1,-10.1,0.3,4.130,1,-17.5,-3.03,Advanced_Radio_Telecom
2,-28.8,-203.2,-51.0,14.7,0.111,1,-232.0,-749.70,Ardent_Communications
3,2.5,-433.1,-6.0,29.3,1.949,1,-430.6,-175.80,At_Home_Corp.
4,26.1,-57.4,-23.5,54.2,0.855,1,-31.3,-1273.70,Convergent_Communications
5,39.2,-111.8,-77.8,10.5,0.168,1,-72.6,-816.90,Covad_Communications
6,-5.4,-105.2,-5.8,38.9,0.028,1,-110.6,-225.62,e.spire
7,-35.2,-92.4,-32.5,48.5,11.280,1,-127.6,-1576.25,eGlobe
9,-22.4,-124.5,-7.9,125.6,1.595,1,-146.9,-992.24,General_Datacomm_Industries
10,24.6,-29.0,-2.0,21.3,1.968,1,-4.4,-42.60,Global_Telesystems
11,6.6,-50.9,-2.6,28.9,0.258,1,-44.3,-75.14,GST_Telecom
12,33.9,-46.5,-17.5,0.9,0.828,1,-12.6,-15.75,Metricom
13,19.1,-66.3,-25.5,22.3,0.460,1,-47.2,-568.65,Net2000_Communications
14,-21.1,-46.0,-26.8,81.4,0.698,1,-67.1,-2181.52,NetVoice_Technologies
15,2.5,-228.7,-6.7,38.6,0.030,1,-226.2,-258.62,PSINet
16,47.0,-78.2,-42.0,4.4,0.168,1,-31.2,-184.80,Rhythms_NetConnections
17,9.1,-40.2,-0.7,81.5,0.522,1,-31.1,-57.05,RSL_Communications
18,43.0,-49.2,-87.4,119.9,2.919,1,-6.2,-10479.26,SSE_Telecom
19,-34.9,-79.0,-13.5,127.8,0.197,1,-113.9,-1725.30,Startec_Global_Communications
20,20.6,-146.3,-36.0,12.6,0.075,1,-125.7,-453.60,Teligent
21,-51.6,-326.1,-98.7,0.9,2.402,1,-377.7,-88.83,U.S._Wireless
22,-93.0,-95.2,-7.3,34.8,0.071,1,-188.2,-254.04,Viatel
23,-127.5,-121.3,6.4,65.7,0.248,1,-248.8,420.48,WebLink_Wireless
24,-1.2,-47.5,-9.7,14.5,0.456,1,-48.7,-140.65,Winstar
26,9.8,-33.8,-7.1,3.2,5.965,0,-24.0,-22.72,Akamai_Technologies
27,37.8,-45.4,-7.1,17.1,3.450,0,-7.6,-121.41,Allegiance_Telecom
35,13.8,-37.6,-13.0,32.3,13.768,0,-23.8,-419.90,Digex
41,20.3,-61.3,1.9,27.0,35.178,0,-41.0,51.30,Openwave_Systems
49,1.1,-39.5,15.7,41.8,1.449,0,-38.4,656.26,Western_Wireless

In [29]:
merged_data[(merged_data['RE/TA'] < -20) & (merged_data['Bankrupt'] ==0)]

,WC/TA,RE/TA,EBIT/TA,S/TA,BVE/BVL,Bankrupt,WC/TA + RE/TA,EBIT/TA*S/TA,Company
26,9.8,-33.8,-7.1,3.2,5.965,0,-24.0,-22.72,Akamai_Technologies
27,37.8,-45.4,-7.1,17.1,3.450,0,-7.6,-121.41,Allegiance_Telecom
35,13.8,-37.6,-13.0,32.3,13.768,0,-23.8,-419.90,Digex
41,20.3,-61.3,1.9,27.0,35.178,0,-41.0,51.30,Openwave_Systems
49,1.1,-39.5,15.7,41.8,1.449,0,-38.4,656.26,Western_Wireless

In [34]:
merged_data.loc[(merged_data['RE/TA'] <- 20) & (merged_data['Bankrupt'] == 0), ['WC/TA', 'EBIT/TA']]

    WC/TA  EBIT/TA
26    9.8     -7.1
27   37.8     -7.1
35   13.8    -13.0
41   20.3      1.9
49    1.1     15.7